maps_server_user: maps_server
maps_server_version: "{{ version }}"
maps_server_home_folder: "/home/{{ maps_server_user }}/{{ maps_server_version }}"
maps_server_db_host: "127.0.0.1"
maps_server_db_port: "5432"
maps_server_db_name: maps_db
github_api_token: test
maps_server_github_api_key: "{{ github_api_token }}"
maps_server_artifact: triplea-maps-server-{{ maps_server_version }}.zip
maps_server_jar_file: triplea-maps-server-{{ maps_server_version }}.jar
maps_server_artifact_download: |
  "{{ github_releases_url }}/{{ maps_server_version }}/{{ maps_server_artifact }}"
maps_server_restart_on_new_deployment: true
