lobby_server_user: lobby_server
lobby_version: "{{ version }}"
lobby_server_home_folder: "/home/{{ lobby_server_user }}/{{ lobby_version }}"
lobby_server_error_report_github_org: "triplea-game"
lobby_server_error_report_github_repo: "test"
lobby_server_error_report_github_token: "test"
lobby_server_db_host: "127.0.0.1"
lobby_server_db_port: "5432"
lobby_server_db_name: lobby_db
lobby_server_db_user: lobby_user
github_api_token: test
lobby_artifact: triplea-lobby-server-{{ lobby_version }}.zip
lobby_jar_file: triplea-lobby-server-{{ lobby_version }}.jar
lobby_artifact_download: |
  "{{ github_releases_url }}/{{ lobby_version }}/{{ lobby_artifact }}"
lobby_restart_on_new_deployment: true

