- name: create service user to run flyway
  user:
    name: flyway
    create_home: yes
    system: yes

- name: Download flyway CLI
  get_url:
    url: "{{ flyway_download_location }}"
    dest: "/home/flyway/flyway-cli.tar.gz"
    mode: "0644"
    checksum: "md5:f5f2683e41cf2581693aad28f69fb4af"
    owner: flyway
    group: flyway

- name: extract flyway CLI
  unarchive:
    copy: no
    src: "/home/flyway/flyway-cli.tar.gz"
    dest: "/home/flyway/"
    creates: "{{ flyway_extracted_location }}"
    owner: flyway
    group: flyway

- name: copy flyway migrations zip if deploying latest
  when: using_latest|bool
  copy:
    src: "migrations.zip"
    dest: "/home/flyway/migrations.zip"
    mode: "0644"
    owner: flyway
    group: flyway

- name: download flyway migrations if deploying a specific version
  when: not using_latest|bool
  get_url:
    url: "{{ migrations_url }}"
    dest: "/home/flyway/migrations.zip"
    owner: flyway
    group: flyway

- name: create migration folders
  file:
    state: directory
    mode: "0755"
    owner: flyway
    group: flyway
    path : "{{ flyway_extracted_location }}/migrations"

- name: extract migrations
  unarchive:
     src: "/home/flyway/migrations.zip"
     remote_src: true
     dest: "{{ flyway_extracted_location }}/migrations"
     mode: "0644"
     owner: flyway
     group: flyway

- name: run flyway
  command: |
     {{ flyway_extracted_location }}/flyway
          -X
          -user={{ item.user }}
          -password={{ item.password }}
          -url={{ item.url }}
          -locations=filesystem:{{ flyway_extracted_location }}/migrations/{{ item.migration_dir }}
          migrate
  register: flyway
  changed_when: '"is up to date. No migration necessary" not in flyway.stdout'
  failed_when: >
     (flyway.rc != 0) or
     ("Successfully validated 0 migrations" in flyway.stdout) or
     ("WARNING: No migrations found. Are your locations set up correctly?" in flyway.stdout)
  loop: "{{ flyway_args }}"
  loop_control:
    label: "{{ item.migration_dir }}"
  no_log: true
