- name: install software properties common
  apt:
    state: present
    name: software-properties-common

- name: install certbot and python for certbot on nginx
  apt:
    update_cache: yes
    name:
      - certbot
      - python3-certbot-nginx

- name: look for certbot generated key file
  stat:
    path: /etc/letsencrypt/live/{{ inventory_hostname }}/cert.pem
  register: has_certbot_pem

- name: run certbot
  command: |
     certbot --nginx -n \
         -m tripleabuilderbot@gmail.com \
         -d {{ inventory_hostname }} \
         --agree-tos \
         --rsa-key-size 4096
  when: has_certbot_pem.stat.exists == false

