server:
  applicationConnectors:
    - type: http
      port: 9090
  adminConnectors:
    - type: http
      port: 9091
database:
  driverClass: org.postgresql.Driver
  user: maps_user
  password: postgres
  url: jdbc:postgresql://localhost:${MAPS_SERVER_DB_PORT:-5433}/maps_db
  properties:
    charSet: UTF-8
  validationQuery: select 1
