name: Check YAML Formatting
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Validate YAML Formatting
      run: ./gradlew validateYamls

