name: Check Links are Valid
on:  pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check Links are Valid
      run: .build/check-links-and-yaml-syntax/check-links

