name: Deploy Prerelease
on:
  push:
    branches:
      - master
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    name: Deploy to Prerelease
    runs-on: Ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: set build version variables
        run: |
          echo "product_version=$BUILD_NUMBER" | tee -a $GITHUB_ENV
      - name: Deploy to Prerelease
        run: |
          pip install ansible==2.9.13
          .build/set-build-number ${{ github.run_number }}
          eval "$(ssh-agent -s)"
          cd infrastructure
          echo "$ANSIBLE_VAULT_PASSWORD" > vault_password
          ./run_ansible --deploy-type minimal --environment prerelease
        env:
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
      - name: Clean up Old Deployments
        run: |
          # Keep only the 5 most recent deployments
          for i in $(ls -t /home/bot/ | grep -v "maps$" | sed -n '5,$p'); do sudo -u bot rm -rfv /home/bot/$i; done;
          for i in $(ls -t /home/lobby_server/ | sed -n '5,$p'); do sudo -u lobby_server rm -rfv /home/lobby_server/$i; done;
